Project::HABTM_Tools.create!([
  {project_id: 1, tool_id: 1},
  {project_id: 1, tool_id: 2},
  {project_id: 2, tool_id: 3},
  {project_id: 2, tool_id: 4},
  {project_id: 2, tool_id: 5},
  {project_id: 2, tool_id: 8},
  {project_id: 3, tool_id: 9},
  {project_id: 10, tool_id: 9},
  {project_id: 21, tool_id: 9},
  {project_id: 22, tool_id: 9},
  {project_id: 20, tool_id: 9},
  {project_id: 20, tool_id: 18},
  {project_id: 18, tool_id: 23},
  {project_id: 18, tool_id: 24},
  {project_id: 18, tool_id: 21},
  {project_id: 18, tool_id: 22},
  {project_id: 19, tool_id: 23},
  {project_id: 19, tool_id: 24},
  {project_id: 19, tool_id: 21},
  {project_id: 19, tool_id: 22},
  {project_id: 4, tool_id: 1},
  {project_id: 4, tool_id: 10},
  {project_id: 5, tool_id: 11},
  {project_id: 5, tool_id: 1},
  {project_id: 5, tool_id: 12},
  {project_id: 5, tool_id: 9},
  {project_id: 5, tool_id: 13},
  {project_id: 5, tool_id: 14},
  {project_id: 5, tool_id: 15},
  {project_id: 5, tool_id: 16},
  {project_id: 6, tool_id: 26},
  {project_id: 6, tool_id: 1},
  {project_id: 6, tool_id: 4},
  {project_id: 6, tool_id: 3},
  {project_id: 6, tool_id: 20},
  {project_id: 6, tool_id: 14},
  {project_id: 6, tool_id: 15},
  {project_id: 6, tool_id: 16},
  {project_id: 6, tool_id: 19},
  {project_id: 7, tool_id: 27},
  {project_id: 7, tool_id: 1},
  {project_id: 7, tool_id: 6},
  {project_id: 7, tool_id: 15},
  {project_id: 7, tool_id: 16},
  {project_id: 8, tool_id: 23},
  {project_id: 9, tool_id: 1},
  {project_id: 9, tool_id: 2},
  {project_id: 9, tool_id: 22},
  {project_id: 11, tool_id: 4},
  {project_id: 11, tool_id: 1},
  {project_id: 11, tool_id: 3},
  {project_id: 11, tool_id: 15},
  {project_id: 11, tool_id: 16},
  {project_id: 12, tool_id: 4},
  {project_id: 12, tool_id: 1},
  {project_id: 12, tool_id: 3},
  {project_id: 12, tool_id: 15},
  {project_id: 12, tool_id: 16},
  {project_id: 12, tool_id: 28},
  {project_id: 13, tool_id: 4},
  {project_id: 13, tool_id: 1},
  {project_id: 13, tool_id: 3},
  {project_id: 13, tool_id: 15},
  {project_id: 13, tool_id: 17},
  {project_id: 13, tool_id: 29},
  {project_id: 13, tool_id: 30},
  {project_id: 13, tool_id: 31},
  {project_id: 13, tool_id: 32},
  {project_id: 14, tool_id: 4},
  {project_id: 14, tool_id: 1},
  {project_id: 14, tool_id: 3},
  {project_id: 14, tool_id: 15},
  {project_id: 14, tool_id: 29},
  {project_id: 14, tool_id: 32},
  {project_id: 15, tool_id: 2},
  {project_id: 15, tool_id: 1},
  {project_id: 16, tool_id: 23},
  {project_id: 16, tool_id: 22},
  {project_id: 17, tool_id: 4},
  {project_id: 17, tool_id: 3},
  {project_id: 17, tool_id: 15},
  {project_id: 17, tool_id: 16}
])
Tool::HABTM_Projects.create!([
  {project_id: 1, tool_id: 1},
  {project_id: 1, tool_id: 2},
  {project_id: 2, tool_id: 3},
  {project_id: 2, tool_id: 4},
  {project_id: 2, tool_id: 5},
  {project_id: 2, tool_id: 8},
  {project_id: 3, tool_id: 9},
  {project_id: 10, tool_id: 9},
  {project_id: 21, tool_id: 9},
  {project_id: 22, tool_id: 9},
  {project_id: 20, tool_id: 9},
  {project_id: 20, tool_id: 18},
  {project_id: 18, tool_id: 23},
  {project_id: 18, tool_id: 24},
  {project_id: 18, tool_id: 21},
  {project_id: 18, tool_id: 22},
  {project_id: 19, tool_id: 23},
  {project_id: 19, tool_id: 24},
  {project_id: 19, tool_id: 21},
  {project_id: 19, tool_id: 22},
  {project_id: 4, tool_id: 1},
  {project_id: 4, tool_id: 10},
  {project_id: 5, tool_id: 11},
  {project_id: 5, tool_id: 1},
  {project_id: 5, tool_id: 12},
  {project_id: 5, tool_id: 9},
  {project_id: 5, tool_id: 13},
  {project_id: 5, tool_id: 14},
  {project_id: 5, tool_id: 15},
  {project_id: 5, tool_id: 16},
  {project_id: 6, tool_id: 26},
  {project_id: 6, tool_id: 1},
  {project_id: 6, tool_id: 4},
  {project_id: 6, tool_id: 3},
  {project_id: 6, tool_id: 20},
  {project_id: 6, tool_id: 14},
  {project_id: 6, tool_id: 15},
  {project_id: 6, tool_id: 16},
  {project_id: 6, tool_id: 19},
  {project_id: 7, tool_id: 27},
  {project_id: 7, tool_id: 1},
  {project_id: 7, tool_id: 6},
  {project_id: 7, tool_id: 15},
  {project_id: 7, tool_id: 16},
  {project_id: 8, tool_id: 23},
  {project_id: 9, tool_id: 1},
  {project_id: 9, tool_id: 2},
  {project_id: 9, tool_id: 22},
  {project_id: 11, tool_id: 4},
  {project_id: 11, tool_id: 1},
  {project_id: 11, tool_id: 3},
  {project_id: 11, tool_id: 15},
  {project_id: 11, tool_id: 16},
  {project_id: 12, tool_id: 4},
  {project_id: 12, tool_id: 1},
  {project_id: 12, tool_id: 3},
  {project_id: 12, tool_id: 15},
  {project_id: 12, tool_id: 16},
  {project_id: 12, tool_id: 28},
  {project_id: 13, tool_id: 4},
  {project_id: 13, tool_id: 1},
  {project_id: 13, tool_id: 3},
  {project_id: 13, tool_id: 15},
  {project_id: 13, tool_id: 17},
  {project_id: 13, tool_id: 29},
  {project_id: 13, tool_id: 30},
  {project_id: 13, tool_id: 31},
  {project_id: 13, tool_id: 32},
  {project_id: 14, tool_id: 4},
  {project_id: 14, tool_id: 1},
  {project_id: 14, tool_id: 3},
  {project_id: 14, tool_id: 15},
  {project_id: 14, tool_id: 29},
  {project_id: 14, tool_id: 32},
  {project_id: 15, tool_id: 2},
  {project_id: 15, tool_id: 1},
  {project_id: 16, tool_id: 23},
  {project_id: 16, tool_id: 22},
  {project_id: 17, tool_id: 4},
  {project_id: 17, tool_id: 3},
  {project_id: 17, tool_id: 15},
  {project_id: 17, tool_id: 16}
])
Project.create!([
  {title: "Alternative Scrolling", description: "because scrolling with your fingers was so 2016", text: "Under Construction", misc: nil, team: "Michael Hu", code_url: "https://github.com/TheMichaelHu/AlternativeScrolling", demo_url: nil, img_url: nil, date: "2017-06-24", type_id: 1, rank: 5},
  {title: "SPADES Data Visualizer", description: "big data, tiny RAM", text: "Under Construction", misc: nil, team: "Michael Hu, Raein Hashemi", code_url: "https://github.com/TheMichaelHu/SPADES_data_visualizer", demo_url: nil, img_url: nil, date: "2015-11-23", type_id: 2, rank: 1},
  {title: "michael (hu)bot", description: "personal assistant for facebook messenger, obscure bordering on esoteric pun", text: "Under Construction", misc: nil, team: "Michael Hu", code_url: "https://github.com/TheMichaelHu/michaelhubot", demo_url: "https://www.facebook.com/michaelhubot", img_url: nil, date: "2017-06-01", type_id: 5, rank: 2},
  {title: "SASE NERC 2016 Website", description: "informational site for 400+ student conference", text: "Under Construction", misc: nil, team: "Michael Hu, Maggie Zhang, Brian Zhu", code_url: nil, demo_url: "http://www.northeastern.edu/sase/conference", img_url: nil, date: "2016-02-13", type_id: 3, rank: 10},
  {title: "ScholarJet", description: "platform for creating a new form of scholarship", text: "Under Construction", misc: nil, team: "ScholarJet Team", code_url: nil, demo_url: "https://scholarjet.com/", img_url: nil, date: "2017-07-08", type_id: 3, rank: 1},
  {title: "Personal Website", description: "it's this, you're looking at it", text: "Under Construction", misc: nil, team: "Michael Hu", code_url: "https://github.com/TheMichaelHu/rails-react-website", demo_url: "http://www.michaelhu.net", img_url: nil, date: "2017-07-27", type_id: 5, rank: 1},
  {title: "Playlistr", description: "it's like chromecasting youtube but free, global, and (now) broken", text: "Under Construction", misc: nil, team: "Tommy Hu, Geoffrey Wong, Matthew Coleman, Michael Hu, Gasper Chan", code_url: "https://github.com/tomxhu/playlistmaker", demo_url: "http://playlstr.herokuapp.com/", img_url: nil, date: "2015-02-09", type_id: 1, rank: 5},
  {title: "Reddit Recommender", description: "item-item collaborative filtering for subreddits", text: "Under Construction", misc: nil, team: "Michael Hu, Yvette Kim, Jordi Lotito", code_url: "https://github.com/TheMichaelHu/redditRecommender", demo_url: nil, img_url: nil, date: "2015-08-24", type_id: 4, rank: 5},
  {title: "Hamster Gambling", description: "it's like roulette but significantly more adorable", text: "Under Construction", misc: nil, team: "Michael Hu", code_url: "https://github.com/TheMichaelHu/HamsterGameVSA", demo_url: "/demos/hamster.jar", img_url: nil, date: "2015-02-15", type_id: 3, rank: 8},
  {title: "Picky Husky", description: "choose NEU dining hall foods to follow, receive a text when they're available", text: "Under Construction", misc: nil, team: "Michael Hu, Naoki Yokoyama, Joanne Truong, Matt Dang", code_url: "https://github.com/TheMichaelHu/PickyHusky", demo_url: "http://pickyhusky.herokuapp.com/", img_url: nil, date: "2016-04-04", type_id: 1, rank: 4},
  {title: "Picky Pusheen", description: "tinder for just finding someone free to run errands with", text: "Under Construction", misc: nil, team: "Michael Hu, Naoki Yokoyama, Joanne Truong, Matt Dang", code_url: "https://github.com/TheMichaelHu/PickyPusheen", demo_url: nil, img_url: nil, date: "2016-09-18", type_id: 1, rank: 1},
  {title: "Rooster", description: "an internet-enabled alarm clock social network that let's you wake up your friends", text: "Under Construction", misc: nil, team: "Michael Hu, Naoki Yokoyama, Joanne Truong, Matt Dang", code_url: "https://github.com/TheMichaelHu/PickyRooster", demo_url: "http://pickyrooster.herokuapp.com/", img_url: nil, date: "2016-10-02", type_id: 1, rank: 10},
  {title: "Pinyinify", description: "chrome extension that replaces Chinese characters with their phonetic spellings", text: "Under Construction", misc: nil, team: "Michael Hu", code_url: "https://github.com/TheMichaelHu/pinyinify", demo_url: "https://chrome.google.com/webstore/detail/pinyinify/ilgkgfbgiempllndljggnmblmcajbcee", img_url: nil, date: "2016-07-28", type_id: 5, rank: 3},
  {title: "Poker Bot", description: "using monte carlo algorithms and machine learning to lose horribly against other poker bots", text: "Under Construction", misc: nil, team: "Pasha Sadikov, Michael Hu, Matt Yudysky", code_url: nil, demo_url: nil, img_url: nil, date: "2016-11-04", type_id: 4, rank: 5},
  {title: "Medium-Rare", description: "simple blogging application like Medium but not as hot right now", text: "Under Construction", misc: nil, team: "Michael Hu, Miranda Chiu, Nancy Li", code_url: "https://github.com/mirdathebirda/Database-Portfolio-Project", demo_url: "https://vast-peak-35773.herokuapp.com/", img_url: nil, date: "2016-12-07", type_id: 4, rank: 6},
  {title: "Book Genre Clustering Using User Ratings", description: "a weak attempt at redefining book genres and subgenres using hierarchial clusting and amazon reviews and less than 8GB of memory", text: "Under Construction", misc: nil, team: "Michael Hu", code_url: "https://github.com/TheMichaelHu/BookGenres", demo_url: nil, img_url: nil, date: "2017-04-19", type_id: 4, rank: 1},
  {title: "Physical Activity Classification", description: "activity classification via blindly throwing accelerometer data at a neural net", text: "Under Construction", misc: nil, team: "Michael Hu", code_url: "https://github.com/TheMichaelHu/SPADES_NN", demo_url: nil, img_url: nil, date: "2016-12-05", type_id: 2, rank: 1},
  {title: "Pointr", description: "a compass on your android wearable that points to eateries and provides Yelp reviews", text: "Under Construction", misc: nil, team: "Oscar Spencer, Nikolai Wotton, Michael Hu, Kevin Luo", code_url: "https://github.com/klevingluo/BeanPotPointr", demo_url: nil, img_url: nil, date: "2015-02-08", type_id: 1, rank: 8},
  {title: "Frisbee Shooter with Computer Vision", description: "an aimbot in real life with frisbees", text: "Under Construction", misc: nil, team: "Anish Thilagar, Michael Hu, Greg Partridge", code_url: nil, demo_url: nil, img_url: nil, date: "2013-01-08", type_id: 3, rank: 8},
  {title: "Space Invaders", description: "a java clone of the original game, but with much more ridiculous gameplay", text: "Under Construction", misc: nil, team: "Michael Hu, Tracey Lum", code_url: nil, demo_url: nil, img_url: nil, date: "2014-04-16", type_id: 4, rank: 9},
  {title: "Ambeyonce", description: "leveraging machine learning to augment your mood with an appropriate Beyonce song", text: "Under Construction", misc: nil, team: "Michael Hu, Nikolai Wotton, Quan Do, Kevin Luo", code_url: "https://github.com/TheMichaelHu/Ambeyonce", demo_url: "https://chrome.google.com/webstore/detail/ambeyonce/afpcaigpflpbboiofbehpfhgjhjjhjmj", img_url: nil, date: "2016-01-24", type_id: 1, rank: 10},
  {title: "Round Robin Bingo", description: "online bingo where everyone takes turns calling out numbers", text: "Under Construction", misc: nil, team: "Michael Hu, Miranda Chiu", code_url: "https://github.com/TheMichaelHu/vsaBingo", demo_url: "http://bingo.michaelhu.net", img_url: nil, date: "2016-03-26", type_id: 3, rank: 3}
])
Tool.create!([
  {name: "JavaScript"},
  {name: "Chrome Extension"},
  {name: "Ruby on Rails"},
  {name: "Ruby"},
  {name: "Facebook"},
  {name: "Youtube"},
  {name: "Yelp"},
  {name: "Chatbot"},
  {name: "Java"},
  {name: "PHP"},
  {name: "Angular 2"},
  {name: "TypeScript"},
  {name: "Java EE"},
  {name: "Webpack"},
  {name: "SQL"},
  {name: "Web Application"},
  {name: "Mobile Application"},
  {name: "Android Wear Application"},
  {name: "ES6"},
  {name: "ESLint"},
  {name: "scikit-learn"},
  {name: "Machine Learning"},
  {name: "Python"},
  {name: "NumPy"},
  {name: "React"},
  {name: "Node.js"},
  {name: "Twilio"},
  {name: "Particle Photon"},
  {name: "3D Printing"},
  {name: "NativeScript"},
  {name: "IoT Device"}
])
Type.create!([
  {name: "hackathon"},
  {name: "research"},
  {name: "organization"},
  {name: "class"},
  {name: "personal"}
])
